version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=pu'
      - 'POSTGRES_PASSWORD=psswd'
      - 'POSTGRES_DB=products-db'
    volumes:
      - 'db:/var/lib/postgresql/data'
volumes:
  db:
    driver: local
  pgadmin_data:
    driver: local
